import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "@/components/navbar/Navbar";
import React from "react";
import "primereact/resources/themes/lara-light-indigo/theme.css";
const inter = Inter({ subsets: ['latin'] })
import 'primereact/resources/primereact.css';

export const metadata: Metadata = {
  title: 'Mosquera',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navbar />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
